### config ###

# See https://www.mkdocs.org/user-guide/configuration/.

INHERIT: !ENV MKDOCS_BASE_CONFIG

### navigation ###

nav:
  - Documentação do Laravel: index.md
  - Prólogo:
      - Notas de Versão: prologo/versoes.md
      - Guia de Atualização: prologo/atualizacao.md
      - Guia de Contribuição: prologo/contribuicoes.md
  - Começando:
      - Instalação: comecando/instalacao.md
      - Configuração: comecando/configuracao.md
      - Estrutura de Diretório: comecando/estrutura.md
      - Front-end: comecando/front-end.md
      - Kits para Iniciantes: comecando/kits-para-iniciantes.md
      - Implantação: comecando/implantacao.md
  - Conceitos de Arquitetura:
      - Ciclo de Vida da Requisição: arquitetura/ciclo-de-vida.md
      - Contêiner de Serviços: arquitetura/conteiner.md
      - Provedores de Serviços: arquitetura/provedores.md
      - Fachadas: facades.md
  - O Básico:
      - Roteamento: routing.md
      - Redirecionamentos: redirects.md
      - Middleware: middleware.md
      - Proteção contra CSRF: csrf.md
      - Controladores: controllers.md
      - Requisições: requests.md
      - Respostas: responses.md
      - Visualizações: views.md
      - Modelos Blade: blade.md
      - Empacotamento de recursos: vite.md
      - Geração de URL: urls.md
      - Sessão: session.md
      - Validação: validation.md
      - Tratamento de erros: errors.md
      - Logging: logging.md
  - Indo mais fundo:
      - Console Artisan: artisan.md
      - Transmissão: broadcasting.md
      - Cache: cache.md
      - Coleções: collections.md
      - Contexto: context.md
      - Contratos: contracts.md
      - Eventos: events.md
      - Armazenamento de arquivos: filesystem.md
      - Auxiliares: helpers.md
      - Cliente HTTP: http-client.md
      - Localização: localization.md
      - E-mail: mail.md
      - Notificações: notifications.md
      - Desenvolvimento de pacotes: packages.md
      - Processos: processes.md
      - Filas: queues.md
      - Limitação de taxa: rate-limiting.md
      - Strings: strings.md
      - Agendamento de tarefas: scheduling.md
  - Segurança:
      - Autenticação: authentication.md
      - Autorização: authorization.md
      - Verificação de e-mail: verification.md
      - Encriptação: encryption.md
      - Hashing: hashing.md
      - Redefinição de senha: passwords.md
  - Banco de dados:
      - Começando: database.md
      - Construtor de consultas: queries.md
      - Paginação: pagination.md
      - Migrações: migrations.md
      - Seeding: seeding.md
      - Redis: redis.md
  - ORM Eloquent:
      - Começando: eloquent.md
      - Relacionamentos: eloquent-relationships.md
      - Coleções: eloquent-collections.md
      - Modificadores / Moldadores: eloquent-mutators.md
      - Recursos de API: eloquent-resources.md
      - Serialização: eloquent-serialization.md
      - Fábricas: eloquent-factories.md
  - Testes:
      - Começando: testing.md
      - Testes HTTP: http-tests.md
      - Testes de console: console-tests.md
      - Testes de navegador: dusk.md
      - Banco de dados: database-testing.md
      - Simulação: mocking.md
  - Pacotes:
      - Breeze: comecando/kits-para-iniciantes.md#laravel-breeze
      - Cashier (Stripe): billing.md
      - Cashier (Paddle): cashier-paddle.md
      - Dusk: dusk.md
      - Envoy: envoy.md
      - Fortify: fortify.md
      - Folio: folio.md
      - Homestead: homestead.md
      - Horizon: horizon.md
      - Jetstream: https://jetstream.laravel.com
      - Mix: mix.md
      - Octane: octane.md
      - Passport: passport.md
      - Pennant: pennant.md
      - Pint: pint.md
      - Precognition: precognition.md
      - Prompts: prompts.md
      - Pulse: pulse.md
      - Reverb: reverb.md
      - Sail: sail.md
      - Sanctum: sanctum.md
      - Scout: scout.md
      - Socialite: socialite.md
      - Telescope: telescope.md
      - Valet: valet.md
  - API:
      - Documentação da API: https://laravel.com/api/11.x/index.html
