### config ###

# See https://www.mkdocs.org/user-guide/configuration/.

INHERIT: !ENV MKDOCS_BASE_CONFIG

### navigation ###

nav:
  - Documentação do Laravel: index.md
  - Prólogo:
      - Notas de Versão: releases.md
      - Guia de Atualização: upgrade.md
      - Guia de Contribuição: contributions.md
  - Configuração:
      - Instalação: installation.md
      - Configuração: configuration.md
      - Homestead: homestead.md
      - Valet: valet.md
  - Tutoriais:
      - Basic Task List: quickstart.md
      - Intermediate Task List: quickstart-intermediate.md
  - O Básico:
      - Roteamento: routing.md
      - Middleware: middleware.md
      - Controladores: controllers.md
      - Requisições: requests.md
      - Respostas: responses.md
      - Visualizações: views.md
      - Blade Templates: blade.md
  - Fundamentos de Arquitetura:
      - Ciclo de Vida da Requisição: lifecycle.md
      - Estrutura de Diretório: structure.md
      - Provedores de Serviços: providers.md
      - Contêiner de Serviços: container.md
      - Contratos: contracts.md
      - Fachadas: facades.md
  - Serviços:
      - Authentication: authentication.md
      - Authorization: authorization.md
      - Console Artisan: artisan.md
      - Cobrança: billing.md
      - Cache: cache.md
      - Coleções: collections.md
      - Elixir: elixir.md
      - Encryption: encryption.md
      - Tratamento de erros e Logging: errors.md
      - Eventos: events.md
      - Sistema de Arquivos / Armazenamento em Nuvem: filesystem.md
      - Hashing: hashing.md
      - Auxiliares: helpers.md
      - Localization: localization.md
      - E-mail: mail.md
      - Desenvolvimento de Pacotes: packages.md
      - Paginação: pagination.md
      - Filas: queues.md
      - Redis: redis.md
      - Sessão: session.md
      - Tarefas SSH: envoy.md
      - Agendamento de Tarefas: scheduling.md
      - Testes: testing.md
      - Validação: validation.md
  - Banco de Dados:
      - Começando: database.md
      - Construtor de Consultas: queries.md
      - Migrações: migrations.md
      - Seeding: seeding.md
  - ORM Eloquent:
      - Começando: eloquent.md
      - Relacionamentos: eloquent-relationships.md
      - Coleções: eloquent-collections.md
      - Modificadores: eloquent-mutators.md
      - Serialização: eloquent-serialization.md
