### config ###

# See https://www.mkdocs.org/user-guide/configuration/.

INHERIT: !ENV MKDOCS_BASE_CONFIG

### navigation ###

nav:
  - Documentação do Laravel: index.md
  - Prólogo:
      - Notas de Versão: releases.md
      - Guia de Atualização: upgrade.md
      - Guia de Contribuição: contributions.md
  - Configuração:
      - Instalação: contributions.md
      - Configuration: configuration.md
      - Homestead: homestead.md
  - O Básico:
      - Roteamento: routing.md
      - Redirecionamentos: redirects.md
      - Middleware: middleware.md
      - Controladores: controllers.md
      - Requisições: requests.md
      - Respostas: responses.md
      - Visualizações: views.md
  - Fundamentos de Arquitetura:
      - Provedores de Serviços: providers.md
      - Contêiner de Serviços: container.md
      - Contratos: contracts.md
      - Fachadas: facades.md
      - Ciclo de Vida da Requisição: lifecycle.md
      - Estrutura da Aplicação: structure.md
  - Serviços:
      - Authentication: authentication.md
      - Authorization: authorization.md
      - Console Artisan: artisan.md
      - Cobrança: billing.md
      - Cache: cache.md
      - Coleções: collections.md
      - Command Bus: bus.md
      - Core Extension: extending.md
      - Elixir: elixir.md
      - Encryption: encryption.md
      - Envoy: envoy.md
      - Tratamento de erros e Logging: errors.md
      - Eventos: events.md
      - Sistema de Arquivos / Armazenamento em Nuvem: filesystem.md
      - Hashing: hashing.md
      - Auxiliares: helpers.md
      - Localization: localization.md
      - E-mail: mail.md
      - Desenvolvimento de Pacotes: packages.md
      - Paginação: pagination.md
      - Filas: queues.md
      - Sessão: session.md
      - Modelos: templates.md
      - Testes Unitários: testing.md
      - Validação: validation.md
  - Banco de Dados:
      - Uso Básico: database.md
      - Construtor de Consultas: queries.md
      - ORM Eloquent: eloquent.md
      - Construtor de Esquemas: schema.md
      - Migrações e Seeding: migrations.md
      - Redis: redis.md
  - Artisan CLI:
    - Visão Geral: artisan.md
    - Desenvolvimento: commands.md
